# github repository actions 페이지에 나타날 이름
name: CI/CD using github actions

# 트리거를 실행할 브랜치 지정
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 깃헙에 있는 프로젝트를 서버로 내려받음
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Use Node.js version 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: yarn deploy
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn deploy

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 rm s3://${{ secrets.AWS_S3_BUCKET }} --recursive
          aws s3 cp --recursive --region ${{ secrets.AWS_REGION }} ./out s3://${{ secrets.AWS_S3_BUCKET }}

      - name: Clear Cache to Cloudfront
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID}} --paths "/*"
